# Generated by Django 3.2.7 on 2021-10-19 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kakao_id', models.CharField(max_length=50, unique=True)),
                ('nickname', models.CharField(blank=True, max_length=50)),
                ('profile_image', models.URLField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('age_range', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
